# Global
loglevel: DEBUG # One of ["TRACE", "DEBUG", "INFO", "SUCCESS", "WARNING", "ERROR", "CRITICAL"]

  # The topics recorded are defined in sim_control/script/node_recorder.py
# Final rosbag is in utils/tmp
record_rosbag: false
record_persistent: false

# Simulation modes
# simple: run the simulator and let it run until user stops it via ctrl+c
# integer value: run simulator for value number of iterations
simulation_mode: simple

landing_threshold: 3.5 #  in meters

# Order of services here is also the order in which services are started
services:
  Vehicle Dynamics:
    jaxguam: "1 Vehicle Dynamics/vehicles/jaxguam/jaxguam.yml"
  Environment Simulation:
    env_sim: "2 Environment Simulation/env_sim/env_sim.yml"
    carla: "2 Environment Simulation/env_sim/carla.yml"
    ground_station: "2 Environment Simulation/ground_station/ground_station.yml"
    sim_control: "2 Environment Simulation/sim_control/sim_control.yml"
  Vehicle Intelligence:
    mapper: "3 Vehicle Intelligence/perception/mapper/mapper.yml"
    rrt_planner: "3 Vehicle Intelligence/path_planner/trajectory_planner/rrt_planner/rrt_planner.yml"
  Communication Interface:
    docker: "4 Communication Interface/docker/docker-compose.yml"

# Test
map: Town02_Opt
spectator_follows_ego_vehicle: False

# Vehicle
ego_vehicle:
  reference_topic: /target/pose
  planner_topic: /target/waypoint
  perception_vel_topic: /controller_node/vel_cmd
  perception_control_topic: /controller_node/tgt_box_rcvd
  # planner_topic: /controller_node/vel_cmd
  planner:
    type: a_star # One of ["simple", "a_star"]
    distance_threshold: 3.5 # distance threshold to the current waypoint
    speed_threshold: 1.0 # minimum speed required when moving between intermediate points
    speed_check_time: 0.5 # time period in s to check the speed
  include: ego_vehicle/jaxguam.yml
  debug: false
  location:
    x: 80
    y: 25
    z: 75
  velocity:
    x: 0
    y: 0
    z: 0

# Adversarial objects
adv_objects:
  enabled: True # One of ["True", "False"]
  complex_objects:
    records_dir: /catkin_ws/src/env_sim/rraaa/script/records # Directory where the recordings are stored
    object_names: []
      #- AdvObject1 for later
      #- AdvObject2 
  objects:
    - pose:
        type: relative # One of ["absolute", "relative"]. If "relative", then relative to the starting pose of the ego vehicle.
        location:
          x: 0
          y: 0
          z: -15
        rotation:
          roll: 0
          pitch: 0
          yaw: 0
      velocity:
        x: 0
        y: 0
        z: 0
      model: uli_cora

# Target point
target:
  type: absolute # One of ["absolute", "relative"]. Absolute -- absolute in CARLA's global coordinate frame. Relative -- relative to the vehicle's starting location.
  x: -80
  y: 75
  z: 25

optional_features:
  include: optional_features/static_obstacles_record.yml
